### ISSUE TITLE
Microsoft Edge cleaner ... and frustration

### ISSUE THREAD

**Issue by theatre-x** [bleachbit/cleanerml#96]
So I (finally) got my hands on a Windows 10 machine and am in the process of writing a cleaner for it.

I am pretty sure I got it to work with Cookies and History so far but the output in BB states that these directories don't really exist.
Blank screen.

Can someone with Win 10 and Edge please test this?
Getting quite pissed off at the roadblock I've run into.

https://github.com/az0/cleanerml/blob/master/pending/edge.xml

Thanks!

**Comment by az0** [comment]
You get a does-not-exist error in both preview and delete modes?

**Comment by theatre-x** [comment]
No I do not. Nothing appears in the output section of the BB main window.

**Comment by theatre-x** [comment]
![bb](https://cloud.githubusercontent.com/assets/3117096/10120374/b6999a44-6485-11e5-9432-943a7429881e.png)

**Comment by Tobias-B-Besemer** [comment]
I'm still not on W10, but you path looks wrong... My rules look e.g. like this:
`<action command="delete" search="glob" path="%LocalAppData%\Packages\AdobeSystemsIncorporated.AdobeReader_*\AC\NVIDIA Corporation\NV_Cache\*"/>
`
...and you try to delete in `\Roaming\Local\Packages\`...
...so I guess the `Local` is to much... ...or you should use `%LocalAppData%\Packages\`, also without `Local`... Is this possible ???

**Comment by Ytrog** [comment]
What is current status? @theatre-x

**Comment by az0** [comment]
We now have a cleaner for Chromium-based Microsoft Edge.

According to Microsoft, Microsoft Edge Legacy [is no longer available](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-access-old-edge)

>Microsoft Edge Legacy will stop receiving security updates on March 9, 2021. You can access Microsoft Edge Legacy until April 13. 

According to the linked blog, users [cannot use the legacy version
](https://techcommunity.microsoft.com/t5/microsoft-365-blog/new-microsoft-edge-to-replace-microsoft-edge-legacy-with-april-s/ba-p/2114224)

>Because Microsoft Edge Legacy will no longer be on devices after you apply this update, the side-by-side experience will no longer be available.

Tobias, thank you for working on this, but I will close this issue because

1. It is not working
2. It has stalled out (sorry for my part in that
3. There is less demand from users for a Edge Legacy cleaner because Microsoft has removed it from all updated systems
4. There is less ability for developers to test cleaners for Edge Legacy for the same reason
